// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace tourismApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240918132743_ModelsAndStructures")]
    partial class ModelsAndStructures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("tourismApp.Models.Entities.Atraction", b =>
                {
                    b.Property<int>("AtractionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AtractionId"));

                    b.Property<decimal>("AtractionCost")
                        .HasColumnType("numeric");

                    b.Property<string>("AtractionDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AtractionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AtractionTypeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAtractionDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("AtractionId");

                    b.ToTable("Atraction");
                });

            modelBuilder.Entity("tourismApp.Models.Entities.Itinerary", b =>
                {
                    b.Property<int>("ItineraryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItineraryID"));

                    b.Property<int>("AtractionId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ItineraryID");

                    b.ToTable("Itinerary");
                });

            modelBuilder.Entity("tourismApp.Models.Entities.Promotion", b =>
                {
                    b.Property<int>("PromotionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PromotionID"));

                    b.Property<int>("AtractionId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPromotionDeleted")
                        .HasColumnType("boolean");

                    b.Property<float>("PromotionCostOrDiscount")
                        .HasColumnType("real");

                    b.Property<string>("PromotionDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PromotionPricingStrategy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PromotionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PromotionID");

                    b.ToTable("Promotion");
                });

            modelBuilder.Entity("tourismApp.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsUserAdmin")
                        .HasColumnType("boolean");

                    b.Property<decimal>("UserAvailableTime")
                        .HasColumnType("numeric");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UserGold")
                        .HasColumnType("numeric");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserPreferredAttractionTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
